root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["make generate", "make styles"]
cmd = "go build -o ./tmp/main ./main.go"
post_cmd = []
bin = "./tmp/main"
full_bin = ""
args_bin = ["runserver"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "testdata", "data", "tools"]
include_dir = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
log = "air.log"
poll = false
poll_interval = 0
delay = 5000
stop_on_error = true
send_interrupt = true
kill_delay = 500
include_file = []
rerun = false
rerun_delay = 500

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false
main_only = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
enabled = true
proxy_port = 8090
app_port = 8000