// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

func NotifyError(title, content string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_NotifyError_6d8d`,
		Function: `function __templ_NotifyError_6d8d(title, content){toastr.error(content, title)
}`,
		Call:       templ.SafeScript(`__templ_NotifyError_6d8d`, title, content),
		CallInline: templ.SafeScriptInline(`__templ_NotifyError_6d8d`, title, content),
	}
}

func NotifySuccess(title, content string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_NotifySuccess_1921`,
		Function: `function __templ_NotifySuccess_1921(title, content){toastr.success(content, title)
}`,
		Call:       templ.SafeScript(`__templ_NotifySuccess_1921`, title, content),
		CallInline: templ.SafeScriptInline(`__templ_NotifySuccess_1921`, title, content),
	}
}
